"""ST5 - Strategy 5 (FZ base): FZ base, band model: Foundation-Zone gate on Strategy 1 rules (1-minute): every Foundation SETUP is carded against a memory of price bands (protected levels and cluster sits) and gated TAKE / WATCH / BLOCK; re-entry only after a confirmed leave of the band. Fills, stop and exits as Strategy 1; REENTER adds a band-reclaim exit.

Ported from v1 strategies/strategy_5.json; the gate is strategies/foundation_zone.py (with v1's FZ modules in
strategies/fz_lib/), shared by ST5-ST8; v2 reproduces v1's trades and FZ payload (tests/test_parity.py).
"""
import core

fzg = core.family("foundation_zone")
ENTRY_RULES, FIRST_SESSION = fzg.ENTRY_RULES, fzg.FIRST_SESSION
refuse, signals, gate, payload = fzg.refuse, fzg.signals, fzg.gate, fzg.payload

SPEC = {'code': 'ST5',
 'name': 'Strategy 5 (FZ base)',
 'description': 'FZ base, band model: Foundation-Zone gate on Strategy 1 rules (1-minute): every Foundation SETUP is '
                'carded against a memory of price bands (protected levels and cluster sits) and gated TAKE / WATCH / '
                'BLOCK; re-entry only after a confirmed leave of the band. Fills, stop and exits as Strategy 1; '
                'REENTER adds a band-reclaim exit.',
 'timeframe': 'minute',
 'warmup_days': 2,
 'rules': {'break_mode': 'touch',
           'choch_mode': 'touch',
           'avwap_weight': 'volume',
           'sl_rule': 'prev_swing',
           'entry_rule': 'fz_v1',
           'exit_rule': 'next_choch'},
 'lot_size': 65,
 'position': {'lots': 1, 'lock': 'strike', 'scale_out': []},
 'types': {'FUT': {'charge_code': 'ZERODHA_NFO_FUT', 'slippage_pts': 5.0},
           'OPT_FUT_SIGNAL': {'charge_code': 'ZERODHA_NFO_OPT', 'slippage_pts': 0.5},
           'OPT_NATIVE': {'charge_code': 'ZERODHA_NFO_OPT', 'slippage_pts': 0.5}},
 'options': {'expiry_types': ['WEEKLY', 'MONTHLY'],
             'expiry_min_days': 1,
             'strike_step': 50,
             'strike_choices': ['ATR2', 'ATM', 'ITM2', 'ITM1', 'OTM1', 'OTM2', 'OTM3', 'OTM4'],
             'strike_default': 'ATR2',
             'atr_period': 14},
 'backtests': [{'label': 'All data',
                'kind': 'all',
                'default': True,
                'notes': 'every session with data, after the warm-up'},
               {'label': 'Design period',
                'kind': 'named',
                'from': '2026-08-26',
                'to': '2026-09-25',
                'notes': 'the rules were built on this window'},
               {'label': 'Unseen test',
                'kind': 'named',
                'from': '2026-07-08',
                'to': '2026-08-25',
                'notes': 'unseen for Foundation rules; used for FZ threshold selection and gate-state design, so not '
                         'out of sample for FZ (volume-blind: not the front month)'},
               {'label': '1M', 'kind': 'preset', 'preset': '1M'},
               {'label': '3M', 'kind': 'preset', 'preset': '3M'}],
 'fz': {'minute': {'band_half_width': {'value': 10, 'source': 'decision:1-2', 'statistic': ''},
                   'birth_a_source': {'value': 'protected_level',
                                      'source': 'evaluation:M03',
                                      'statistic': 'every_swing tiles the tape: 92 swings/session, 97% of swing births '
                                                   'merge (1m, all data 2026-07-01..09-25)',
                                      'note': 'every_swing is a diagnostic option, not seeded'},
                   'birth_b': {'value': 'band',
                               'source': 'decision:1',
                               'statistic': '',
                               'note': "re-confirmation pending (evaluation A5); alternative 'flag'"},
                   'cluster_bars': {'value': 10, 'source': 'decision:1', 'statistic': ''},
                   'cluster_width': {'value': 20, 'source': 'decision:1', 'statistic': ''},
                   'merge_overlap': {'value': 0.5, 'source': 'decision:1', 'statistic': ''},
                   'zone_max_age_sessions': {'value': None,
                                             'source': 'evaluation:D06',
                                             'statistic': 'age-out does not buy reproducibility: age 2 still leaves '
                                                          '18/55 design cards (3 gates) start-dependent, never-delete '
                                                          '55/55 (1m, standalone Design run vs All-data slice)'},
                   'room_model': {'value': 'bands',
                                  'source': 'evaluation:v2 (base model, no behaviour change)',
                                  'statistic': '',
                                  'note': "'rooms' is the v2 living indicator (Strategies 7, 8)"},
                   'drift_birth': {'value': True,
                                   'source': 'evaluation:v2 (base model, no behaviour change)',
                                   'statistic': ''},
                   'room_overlap': {'value': 'supersede',
                                    'source': 'evaluation:v2 (base model, no behaviour change)',
                                    'statistic': '',
                                    'note': 'rooms only; not read by the band model'},
                   'same_session_overlap': {'value': 'keep_older',
                                            'source': 'user decision 2026-09-27 call 2 (base model, no behaviour '
                                                      'change)',
                                            'statistic': '',
                                            'note': 'rooms only; not read by the band model'},
                   'session_visit_rule': {'value': 'any_close',
                                          'source': 'user decision 2026-09-28 (base model, no behaviour change)',
                                          'statistic': '',
                                          'note': 'rooms only; not read by the band model'},
                   'adjacent_birth': {'value': 'allow',
                                      'source': 'user decision 2026-09-28 (base model, no behaviour change)',
                                      'statistic': '',
                                      'note': 'rooms only; not read by the band model'},
                   'defend_half': {'value': 'off',
                                   'source': 'user decision 2026-09-28 (base model, no behaviour change)',
                                   'statistic': '',
                                   'note': 'off: the defend TAKE as built (an edge event only)'},
                   'room_edges': {'value': 'half_width',
                                  'source': 'user decision 2026-09-28b (base model, no behaviour change)',
                                  'statistic': '',
                                  'note': 'rooms only; not read by the band model'},
                   'absorb_rule': {'value': 'overlap',
                                   'source': 'user decision 2026-09-28b (base model, no behaviour change)',
                                   'statistic': '',
                                   'note': 'rooms only; not read by the band model'},
                   'defend_direction': {'value': 'any',
                                        'source': 'user decision 2026-09-28b (base model, no behaviour change)',
                                        'statistic': '',
                                        'note': 'any: the defend TAKE as built'},
                   'same_day_replace': {'value': 'off',
                                        'source': 'user decision 2026-09-28c (base model, no behaviour change)',
                                        'statistic': '',
                                        'note': 'rooms only; not read by the band model'},
                   'room_max_age_sessions': {'value': None,
                                             'source': 'evaluation:v2 (base model, no behaviour change)',
                                             'statistic': '',
                                             'note': 'null: zones are never retired'},
                   'visit_min_bars': {'value': 1,
                                      'source': 'evaluation:v2 (base model, no behaviour change)',
                                      'statistic': '',
                                      'note': '1: every stay is a visit (no touches)'},
                   'accept_bars': {'value': 10, 'source': 'spec:s2', 'statistic': ''},
                   'accept_vol_ratio': {'value': 0.8, 'source': 'spec:s2', 'statistic': ''},
                   'thin_ratio': {'value': 0.5, 'source': 'spec:s2', 'statistic': ''},
                   'first_print_min_bars': {'value': 3, 'source': 'decision:7', 'statistic': ''},
                   'hunt_form': {'value': 'close',
                                 'source': 'evaluation:M13',
                                 'statistic': 'one close outside then a close back inside; a wick pierce with the '
                                              'close inside is routine (29% of 1m inside bars)'},
                   'hunt_max_bars': {'value': 3, 'source': 'spec:s2', 'statistic': ''},
                   'hunt_min_depth_atr': {'value': None,
                                          'source': 'evaluation:M13',
                                          'statistic': 'not used by the close form'},
                   'hunt_burst': {'value': 1.5,
                                  'source': 'evaluation:M13',
                                  'statistic': 'no tape statistic; skipped when volume NA'},
                   'reject_tol': {'value': 2,
                                  'source': 'evaluation:M15',
                                  'statistic': 'wick within eps of an edge, not beyond: 3.7/22/39/75% of inside bars '
                                               'at 0/1/2/5 pts (1m, live protected-level band, all data)'},
                   'leave_closes': {'value': 2, 'source': 'spec:s2/s4', 'statistic': ''},
                   'leave_ttl_bars': {'value': 15,
                                      'source': 'evaluation:M11',
                                      'statistic': "the spec's 15-minute window by analogy"},
                   'leave_far_side': {'value': 'block_list',
                                      'source': 'evaluation:D02/C02',
                                      'statistic': '1m branch-1 TAKEs: any ~75, block_list ~10-16, no_band ~2 (all '
                                                   'data)',
                                      'note': "user decision pending; alternatives 'any', 'no_band'"},
                   'fade_block_bars': {'value': 15, 'source': 'decision:6', 'statistic': ''},
                   'fade_scope': {'value': 'ref_band',
                                  'source': 'evaluation:C03',
                                  'statistic': 'fade block on any band blocks 40% of 1m SETUPs, on the card band 2%'},
                   'defend_window_bars': {'value': 15,
                                          'source': 'evaluation:M18',
                                          'statistic': "the spec's 15-minute window by analogy"},
                   'open_bars': {'value': 10, 'source': 'spec:s3', 'statistic': '', 'note': 'first 10 minutes'},
                   'open_quiet_bars': {'value': 10,
                                       'source': 'evaluation:M25',
                                       'statistic': "the spec's first 10 minutes"},
                   'open_sit_closes': {'value': 3,
                                       'source': 'evaluation:M25',
                                       'statistic': '',
                                       'note': 'open guard: the pierced band has fewer than this many closes inside '
                                               "today ('no sit'); the build plan states it inline, moved here so no "
                                               'number lives in fz.py'},
                   'open_window_until': {'value': '09:25', 'source': 'spec:s3', 'statistic': ''},
                   'no_entry_from': {'value': '15:20', 'source': 'spec:s3, decision:10', 'statistic': ''},
                   'cancel_inside_bars': {'value': 5, 'source': 'spec:s4', 'statistic': '', 'note': '5 minutes'},
                   'edge_watch': {'value': 'ref_band',
                                  'source': 'evaluation:D03',
                                  'statistic': 'REENTER ~64 with ref_band vs ~6 with containing_band (1m, all data)',
                                  'note': "alternative 'containing_band'"},
                   'volume_base': {'value': 'first',
                                   'source': 'spec:s2, decision:4',
                                   'statistic': '',
                                   'note': "C01: 'previous' is a later variant"},
                   'reenter_fill': {'value': 'confirm_bar', 'source': 'evaluation:M20', 'statistic': ''},
                   'control_draws': {'value': 2000, 'source': 'evaluation:M43', 'statistic': ''},
                   'control_seed': {'value': 'fz', 'source': 'evaluation:M43', 'statistic': ''}}}}
